### ISSUE TITLE
[UI] Sidebar should be fixed

### ISSUE THREAD

**Issue by niteshkumarniranjan** [Eugeny/terminus#1040]
The sidebar should be fixed and only body should be scrollable for a better UX.

**Comment by IgnusG** [comment]
This needs to be applied:
```css
settings-tab .tab-content {
    height: 100%;
}
```

You can add it to custom CSS as a quick-fix in the mean time
