### ISSUE TITLE
How to use cmder?

### ISSUE THREAD

**Issue by cdwmhcc** [Eugeny/terminus#1276]
![image](https://user-images.githubusercontent.com/8030134/61575836-92f08a80-ab03-11e9-98e8-cae57cd3d45d.png)

That's not going to work.

**Comment by cdwmhcc** [comment]
```
terminal:
  profile: cmder
  profiles:
    - name: Cmder
        args:
          - '--login'
          - /k
          - '%ConEmuDir%\\..\\init.bat'
        env:
          ConEmuDir: 'D:\\Tools\\cmder\\vendor\\conemu-maximus5\\'
```
