### ISSUE TITLE
Custom styling

### ISSUE THREAD

**Issue by jwintz** [Eugeny/terminus#134]
Hello,

I'm trying to reproduce the emac's excellent doom-one-theme inspired by atom.

I came up with the following CSS

```css
app-root > .content,
app-root > .content .tab-bar > .tabs tab-header,
app-root > .content .tab-bar > .tabs tab-header.active,
tab-body,
x-screen
{
background-color: #282c34 !important;
}

settings-tab > ngb-tabset > .nav
{
background-color: #21242b !important;;
border-right: 1px solid #222222;
}

.tab-body,
.tab-content {
  background-color: #282c34 !important;
}

app-root > .content .tab-bar .drag-space,
app-root > .content.tabs-on-top .tab-bar,
.btn
{
  background: #21242b !important;
}
```

However:

* The custom stylesheet is only applied whenever I change it, it is not loaded at startup
* I cannot figure out how the change the `x-screen` background color, as show on the screenshot

Using alpha 20 on MacOSX High Sierra.

<img width="1642" alt="screen shot 2017-07-18 at 18 48 49" src="https://user-images.githubusercontent.com/3277054/28329583-a645b330-6bea-11e7-9b4d-67b5e5e66f95.png">
