### ISSUE TITLE
Question about background in themes

### ISSUE THREAD

**Issue by MattMattV** [Eugeny/terminus#140]
I would like to make https://github.com/LazoCoder/Pokemon-Terminal work with Terminus, would you give me some information on how feasible it is ? I can make some pull requests to Terminus by the way.

Thanks in advance

**Comment by Eugeny** [comment]
This is totally possible, you just need to style the `x-screen` tag, e.g., paste this into your Custom CSS:

```css
x-screen {
    background: url(http://i.imgur.com/lo6Td1n.jpg);
    background-size: cover;
}
```
