### ISSUE TITLE
The HotKey Setting Interface Jitter Problem

### ISSUE THREAD

**Issue by yangjz1125** [Eugeny/terminus#1412]
The hotkey setting interface will shake when I put the cursor on the edge of button.
My OS is Windows 10, and here is my profile.

```
hotkeys:
  shell: {}
  profile:
    powershell:
      - - Shift-P
        - Shift-S
    cmd-clink:
      - - Shift-C
        - Shift-M
        - Shift-D
    git-bash:
      - - Shift-G
        - Shift-I
        - Shift-T
  toggle-window:
    - - Shift-V
  search:
    - - Ctrl-F
  close-tab:
    - - Ctrl-W
  rename-tab:
    - - Ctrl-R
  new-tab:
    - - Shift-N
  next-tab: []
  previous-tab: []
  settings: []
  ssh: []
  copy:
    - - Ctrl-Shift-C
  paste:
    - - Ctrl-Shift-V
  home:
    - - Ctrl-Q
    - - Home
  end:
    - - Ctrl-E
    - - End
  previous-word:
    - - Ctrl-A
  next-word:
    - - Ctrl-D
  delete-previous-word: []
  delete-next-word: []
  clear:
    - - Ctrl-X
  zoom-in: []
  zoom-out: []
  reset-zoom: []
  new-window: null
ssh: {}
terminal:
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
appearance: {}
enableWelcomeTab: false
```

![picture1](https://user-images.githubusercontent.com/33955566/63500389-59dd7880-c4fc-11e9-95f4-8141a13f800f.png)
Here is the video.
[Problem.zip](https://github.com/Eugeny/terminus/files/3529158/Problem.zip)
