### ISSUE TITLE
meta is not sent to the shell, with or without "Alt as Meta key"

### ISSUE THREAD

**Issue by nicexe** [Eugeny/terminus#1560]
First of all I'm on Windows 10.
Alt+up and Alt+down does not work on weechat regardless of the "Alt as Meta key" setting.
I tried all frontend options with both "Alt as Meta key" enabled and disabled.
I made sure to restart terminus between tests and the problem still persists.

This is what my configuration looks like:
```
hotkeys:
  profile: {}
  shell: {}
ssh: {}
terminal:
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  background: theme
  environment: {}
  profile: default-powershell-core
  bell: audible
  autoOpen: true
  copyOnSelect: true
  altIsMeta: true
  fallbackFont: STIX Two Math
  useConPTY: true
  frontend: xterm
  ligatures: true
appearance:
  theme: Compact
  vibrancy: true
  vibrancyType: fluent
  frame: thin
  opacity: 1
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist:
  - relaxed-theme
  - theme-gruvbox
  - theme-hype
  - theme-windows10
  - altair
  - quick-cmds
qc: {}
titleControl: {}

```
