### ISSUE TITLE
[Feature Request] Hide close button on tabs

### ISSUE THREAD

**Issue by x1nas** [Eugeny/terminus#1641]
Tabs can be closed with the middle mouse button.
Need an option in the Settings to hide close button on tabs.

**Comment by zenwan** [comment]
+1

**Comment by Eugeny** [comment]
You can do that with custom CSS (Settings > Application):

```css
tab-header button { display: none !important; }
```
