### ISSUE TITLE
No keyboard input. 

### ISSUE THREAD

**Issue by th3jesta** [Eugeny/terminus#1691]
Version: 1.0.92
Platform: darwin 18.7.0
Plugins: none

Keyboard input does not work at all. I can't type in my local terminal or in SSH. The macOS system terminal works. Originally, I copied the terminus config from my old laptop, and to troubleshoot I reverted to default, but still with no luck. Here is my current config:

<details>
<summary>Config file</summary>

```
hotkeys:
  settings:
    - '⌘-,'
  ssh:
    - Alt-S
  ctrl-c:
    - Ctrl-C
  copy:
    - ⌘-C
  paste:
    - ⌘-V
  clear:
    - ⌘-K
  zoom-in:
    - ⌘-=
    - ⌘-Shift-=
  zoom-out:
    - ⌘--
    - ⌘-Shift--
  reset-zoom:
    - ⌘-0
  new-tab:
    - ⌘-T
    - ⌘-N
  home:
    - ⌘-Left
    - Home
  end:
    - ⌘-Right
    - End
  previous-word:
    - ⌥-Left
  next-word:
    - ⌥-Right
  delete-previous-word:
    - ⌥-Backspace
  delete-next-word:
    - ⌥-Delete
  search:
    - ⌘-F
  shell:
    __nonStructural: true
  profile:
    __nonStructural: true
  new-window:
    - ⌘-N
  toggle-window:
    - Ctrl+Space
  toggle-fullscreen:
    - Ctrl+⌘+F
  close-tab:
    - ⌘-W
  toggle-last-tab: []
  rename-tab:
    - ⌘-R
  next-tab:
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Tab
  tab-1:
    - ⌘-1
  tab-2:
    - ⌘-2
  tab-3:
    - ⌘-3
  tab-4:
    - ⌘-4
  tab-5:
    - ⌘-5
  tab-6:
    - ⌘-6
  tab-7:
    - ⌘-7
  tab-8:
    - ⌘-8
  tab-9:
    - ⌘-9
  tab-10:
    - ⌘-0
  split-right:
    - ⌘-Shift-D
  split-bottom:
    - ⌘-D
  split-left: []
  split-top: []
  pane-nav-right:
    - ⌘-⌥-Right
  pane-nav-down:
    - ⌘-⌥-Down
  pane-nav-up:
    - ⌘-⌥-Up
  pane-nav-left:
    - ⌘-⌥-Left
  close-pane:
    - ⌘-Shift-W
ssh:
  connections:
    - name: [redacted]
      host: [redacted]
      port: 22
      user: [redacted]
      algorithms:
        hmac:
          - hmac-sha2-256
          - hmac-sha2-512
          - hmac-sha1
        kex:
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha1
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ssh-rsa
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
      privateKey: [redacted]
      group: null
    - name: [redacted]
      host: [redacted]
      port: [redacted]
      user: [redacted]
      algorithms:
        hmac:
          - hmac-sha2-256
          - hmac-sha2-512
          - hmac-sha1
        kex:
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha1
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ssh-rsa
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
      scripts: []
      group: null
      privateKey: [redacted]
    - name: [redacted]
      host: [redacted]
      port: 22
      user: [redacted]
      algorithms:
        hmac:
          - hmac-sha2-256
          - hmac-sha2-512
          - hmac-sha1
        kex:
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha1
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ssh-rsa
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
      scripts: []
      privateKey: [redacted]
      group: null
    - name: [redacted]
      host: [redacted]
      port: 22
      user: [redacted]
      algorithms:
        hmac:
          - hmac-sha2-256
          - hmac-sha2-512
          - hmac-sha1
        kex:
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha1
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ssh-rsa
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
      scripts: []
      privateKey: [redacted]
      group: null
    - name: [redacted]
      host: [redacted]
      port: 22
      user: [redacted]
      algorithms:
        hmac:
          - hmac-sha2-256
          - hmac-sha2-512
          - hmac-sha1
        kex:
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha1
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ssh-rsa
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
      scripts: []
      privateKey: [redacted]
      group: null
    - name: [redacted]
      host: [redacted]
      port: 22
      user: [redacted]
      algorithms:
        hmac:
          - hmac-sha2-256
          - hmac-sha2-512
          - hmac-sha1
        kex:
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha1
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ssh-rsa
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
      scripts: []
      privateKey: [redacted]
      group: null
terminal:
  font: Fira Code
  shell: default
  profile: user-default
  frontend: xterm
  autoOpen: false
  fontSize: 18
  fallbackFont: null
  linePadding: 0
  bell: 'off'
  bracketedPaste: false
  background: theme
  ligatures: true
  cursor: beam
  cursorBlink: true
  customShell: ''
  rightClick: menu
  copyOnSelect: false
  scrollOnInput: true
  workingDirectory: ''
  alwaysUseWorkingDirectory: false
  altIsMeta: false
  colorScheme:
    __nonStructural: true
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  customColorSchemes: []
  environment: {}
  profiles: []
  useConPTY: true
  recoverTabs: true
pluginBlacklist: []
appearance:
  dock: 'off'
  dockScreen: current
  dockFill: 0.5
  tabsLocation: top
  cycleTabs: true
  theme: Standard
  frame: thin
  css: '/* * { color: blue !important; } */'
  opacity: 1
  vibrancy: true
  vibrancyType: blur
enableAnalytics: false
enableWelcomeTab: false
electronFlags:
  - - force_discrete_gpu
    - '0'
enableAutomaticUpdates: true
```

</details>

And in case it's relevant, here's my bash profile:

<details>
<summary>Bash profile</summary>

```
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'
```

</details>

Any help would be greatly appreciated. I love this app!

**Comment by th3jesta** [comment]
I actually found this error every time a key is pressed in the debug tools:
```
errors.ts:35 ERROR TypeError: value.map is not a function
    at HotkeysService.getHotkeysConfigRecursive (hotkeys.service.ts:207)
    at HotkeysService.getHotkeysConfigRecursive (hotkeys.service.ts:198)
    at HotkeysService.getHotkeysConfig (hotkeys.service.ts:190)
    at HotkeysService.getCurrentPartiallyMatchedHotkeys (hotkeys.service.ts:118)
    at keyboardEventHandler (xtermFrontend.ts:61)
    at t.eval [as _customKeyEventHandler] (xtermFrontend.ts:81)
    at t._keyDown (VM697 57:1)
    at HTMLTextAreaElement.eval (VM697 57:1)
    at ZoneDelegate.invokeTask (/Users/jesse.wisener/Applications/Terminus.app/Contents/Resources/app.asar/node_modules/zone.js/dist/zone.js:423)
    at Object.onInvokeTask (ng_zone.ts:262)
```

**Comment by Eugeny** [comment]
Can you try removing following from the config file?

```
  shell:
    __nonStructural: true
  profile:
    __nonStructural: true
```
