### ISSUE TITLE
Don't see run as administrator options in profile settings

### ISSUE THREAD

**Issue by epiecs** [Eugeny/terminus#1712]
Hi,

I installed terminus for all users, the latest version 1.0.92

When adding a profile I do not get the option Run as administrator. When I manually add this to the config in a clean install with a profile it wont work as well.

Starting terminus as administrator also won't work

![image](https://user-images.githubusercontent.com/124507/67757948-0aa44e80-fa3d-11e9-9f2c-a639ab4d0c3c.png)

```yaml
hotkeys:
  profile:
    cmd-clink: []
    powershell:
      - - Ctrl-Shift-P
  shell: {}
  close-pane: []
ssh: {}
terminal:
  colorScheme:
    name: OneHalfDark
    foreground: '#dcdfe4'
    background: '#282c34'
    cursor: '#a3b3cc'
    colors:
      - '#282c34'
      - '#e06c75'
      - '#98c379'
      - '#e5c07b'
      - '#61afef'
      - '#c678dd'
      - '#56b6c2'
      - '#dcdfe4'
      - '#282c34'
      - '#e06c75'
      - '#98c379'
      - '#e5c07b'
      - '#61afef'
      - '#c678dd'
      - '#56b6c2'
      - '#dcdfe4'
  ligatures: true
  font: Menlo
  background: theme
  cursor: block
  environment: {}
  profile: powershell-adm
  profiles:
    - name: PowerShell ADM
      sessionOptions:
        command: powershell.exe
        args:
          - '-nologo'
        env:
          TERM: cygwin
        runAsAdministrator: true
  rightClick: paste
  copyOnSelect: true
  autoOpen: true
  recoverTabs: true
appearance:
  theme: Standard
  vibrancy: true
  opacity: 1
  frame: thin
  tabsLocation: top
  dock: 'off'
enableAnalytics: false
enableWelcomeTab: false

```

Best regards,

Gregory
