### ISSUE TITLE
Settings gear does not work

### ISSUE THREAD

**Issue by Xolsurf3r** [Eugeny/terminus#1752]
Version: 1.0.92
Platform: win32 10.0.18362
Plugins: none

After latest update the settings gear does not work and saved SSH entries are not shown the list anymore.
It also seem that terminus is using a lot of CPU than usual.

Thanks for looking into.

**Comment by Eugeny** [comment]
Please paste your config file content here (see https://github.com/Eugeny/terminus/wiki/Config-file)

**Comment by metya** [comment]
same problem

**Comment by Onepamopa** [comment]
@metya paste config. Settings works for me.

**Comment by metya** [comment]
@Onepamopa 
 <details>
  <summary>Config</summary>

```
hotkeys:
  shell: {}
  profile: {}
  close-tab:
    - - Ctrl-Shift-W
    - - Ctrl-W
  toggle-last-tab:
    - - Ctrl-Tab
  paste:
    - - Ctrl-Shift-V
    - - Ctrl-V
  toggle-window: []
  tab-1: []
  tab-2: []
  tab-3: []
  tab-4: []
  tab-5: []
  tab-6: []
  tab-7: []
  tab-8: []
  tab-9: []
  tab-10: []
ssh:
  connections:
    - name: astral
      host: 37.221.201.222
      port: 8081
      user: metya
      algorithms:
        hmac:
          - hmac-sha2-256
          - hmac-sha2-512
          - hmac-sha1
        kex:
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha1
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ssh-rsa
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
      scripts: []
      group: null
      keepaliveInterval: 240
    - name: mts_astral
      host: 89.22.184.14
      port: 22
      user: nvidia
      algorithms:
        hmac:
          - hmac-sha2-256
          - hmac-sha2-512
          - hmac-sha1
        kex:
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha1
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ssh-rsa
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
      scripts: []
      group: null
terminal:
  colorScheme:
    name: Ubuntu
    foreground: '#eeeeec'
    background: '#300a24'
    cursor: '#bbbbbb'
    colors:
      - '#2e3436'
      - '#cc0000'
      - '#4e9a06'
      - '#c4a000'
      - '#3465a4'
      - '#75507b'
      - '#06989a'
      - '#d3d7cf'
      - '#555753'
      - '#ef2929'
      - '#8ae234'
      - '#fce94f'
      - '#729fcf'
      - '#ad7fa8'
      - '#34e2e2'
      - '#eeeeec'
  bell: visual
  autoOpen: false
  environment: {}
  background: theme
  profile: cmder
  fontSize: 16
  ligatures: true
  font: Ubuntu Mono derivative Powerline Bold
appearance:
  opacity: 1
  frame: thin
  dock: 'off'
  theme: Hype
enableWelcomeTab: false
qc: {}
pluginBlacklist:
  - save-output
  - quick-cmds

```

</details>
