### ISSUE TITLE
got "Request type `session:None` not support now" error when using jumpserver

### ISSUE THREAD

**Issue by 459217974** [Eugeny/terminus#1758]
I know this is not terminus's problem, but I can not resolve this problem by myself.
We using jumpserver (https://github.com/jumpserver/jumpserver) to connect to some machines and my config is here

```yaml
- name: Name
      host: jumpserver.no.sample.com
      port: 2222
      user: someone
      algorithms:
        hmac:
          - hmac-sha2-256
          - hmac-sha2-512
          - hmac-sha1
        kex:
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha1
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ssh-rsa
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
      privateKey: /Users/someone/.ssh/id_rsa
      scripts:
        - expect: Opt>
          send: 10.18.0.82
        - expect: $
          send: sudo -i
      group: Others
      keepaliveInterval: 10000
      keepaliveCountMax: -1
      readyTimeout: -1
```

then I got this error :
Request type `session:None` not support now

But the command `ssh someone@jumpserver.no.sample.com -p 2222` is worked

So, Anyone can help me?

forgive my poor english
thanks a lot
