### ISSUE TITLE
Settings editing issue

### ISSUE THREAD

**Issue by 1Stedy** [Eugeny/terminus#1785]
I have a problem saving new hosts to ssh connection list. Newly added hosts exist until application restarted. Also settings button not working until restart
My list looks like this:
![69127545-7a957a00-0abb-11ea-8a9a-4aa90c4f489a](https://user-images.githubusercontent.com/16520060/69638638-20248c80-106c-11ea-8e43-1f048be90b11.png)

**Comment by 1Stedy** [comment]
I found that delete not working too. Where do settings saved?

**Comment by Eugeny** [comment]
Could you please post your config file (https://github.com/Eugeny/terminus/wiki/Config-file) and exact steps that lead to this?

**Comment by 1Stedy** [comment]
I can't find steps to reproduce this. Just one day I got this issue. Application was updated several times and one time reinstalled. Maybe it has some influence at issue.
Here is my config (I cleared ssh section, only one host leaves, they all have same options)
```
hotkeys:
  shell: {}
  profile: {}
ssh:
  connections:
    - name: openvpn
      host: openvpn-1.example.com
      port: 22
      user: user
      algorithms:
        hmac:
          - hmac-sha2-256
          - hmac-sha2-512
          - hmac-sha1
        kex:
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha1
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ssh-rsa
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
      scripts: []
      group: vpn
terminal:
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  environment: {}
  bell: 'off'
  bracketedPaste: true
  copyOnSelect: false
  profile: default-powershell
  frontend: xterm
appearance:
  theme: Standard
  tabsLocation: top
  frame: thin
  vibrancy: false
  opacity: 1
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist:
  - shell-selector
```
