### ISSUE TITLE
Strange behaviors on Ubuntu 17.04

### ISSUE THREAD

**Issue by huyvohcmc** [Eugeny/terminus#18]
1. I don't know why but sometimes the app's window doesn't show up unless you maximize its window in the first few seconds when it was launch.

2. It doesn't keep the latest terminal size, always reset to this everytime I re-open it:
![image](https://user-images.githubusercontent.com/17645203/27758617-0a1d961c-5e43-11e7-82c2-9915a5b9fe95.png)

3. It cannot be closed using the x button. The only way I can close it is to kill the process in `htop`.

**Comment by Eugeny** [comment]
Could you please post your `config.yaml` and `window.json`, both found in `~/.config/terminus`?

**Comment by huyvohcmc** [comment]
config.yaml

```
terminal:
  customColorSchemes:
    - __nonStructural: true
      name: Material
      foreground: '#eceff1'
      background: 'rgba(38, 50, 56, 1)'
      cursor: '#FFCC00'
      colors:
        - '#000000'
        - '#D62341'
        - '#9ECE58'
        - '#FAED70'
        - '#396FE2'
        - '#BB80B3'
        - '#2DDAFD'
        - '#d0d0d0'
        - 'rgba(255, 255, 255, 0.2)'
        - '#FF5370'
        - '#C3E88D'
        - '#FFCB6B'
        - '#82AAFF'
        - '#C792EA'
        - '#89DDFF'
        - '#ffffff'
  colorScheme:
    name: MaterialDark
    foreground: '#e5e5e5'
    background: '#232322'
    cursor: '#16afca'
    colors:
      - '#212121'
      - '#b7141f'
      - '#457b24'
      - '#f6981e'
      - '#134eb2'
      - '#560088'
      - '#0e717c'
      - '#efefef'
      - '#424242'
      - '#e83b3f'
      - '#7aba3a'
      - '#ffea2e'
      - '#54a4f3'
      - '#aa4dbc'
      - '#26bbd1'
      - '#d9d9d9'
  shell: ~default-shell~
  background: theme
  fontSize: 14
hotkeys: {}
appearance:
  frame: native
  dock: 'off'
  tabsLocation: top
  theme: Standard
```

window.json

```
{
	"windowBoundaries": {
		"x": 207,
		"y": 114,
		"width": 890,
		"height": 539
	}
}
```
