### ISSUE TITLE
linux menuconfig display abnormally with custom colors

### ISSUE THREAD

**Issue by CyrilTaylor** [Eugeny/terminus#1940]
Version: 1.0.97
Platform: win32 10.0.18363
Plugins: none

Terminus:
![snipaste_20191230_150059](https://user-images.githubusercontent.com/12631466/71571454-462ec800-2b15-11ea-9dd2-22d3c2f6a529.png)

VS Code:
![snipaste_20191230_150118](https://user-images.githubusercontent.com/12631466/71571456-4f1f9980-2b15-11ea-8e5f-5b40a500c24f.png)

Configs:
```yaml
hotkeys:
  shell: {}
  profile: {}
terminal:
  colorScheme:
    name: sion
    foreground: '#e5e5e5'
    background: '#1e1e1e'
    cursor: '#00B2CB'
    colors:
      - '#000000'
      - '#FF4000'
      - '#3FD993'
      - '#F0F000'
      - '#32B7FF'
      - '#A132BC'
      - '#00B2CB'
      - '#e5e5e5'
      - '#4D4D4D'
      - '#F30E58'
      - '#54DD9F'
      - '#FFFF00'
      - '#00A5FF'
      - '#C87DD7'
      - '#4BCADD'
      - '#E5E5E5'
  environment: {}
  bell: 'off'
  profile: default-wsl-ubuntu
  frontend: xterm-webgl
  font: SauceCodePro NF Regular
  ligatures: true
  fontSize: 12
  background: theme
  cursor: beam
  fallbackFont: FangSong Regular
  copyOnSelect: true
  useConPTY: true
  autoOpen: false
  profiles: []
appearance:
  theme: Compact
  tabsLocation: top
  vibrancy: true
  vibrancyType: blur
  opacity: 1
  frame: thin
  dock: 'off'
  css: ''
enableWelcomeTab: false
```
