### ISSUE TITLE
Terminus broken after new install

### ISSUE THREAD

**Issue by Stanzilla** [Eugeny/terminus#1955]
I used Terminus a while back but had since uninstalled it. Tried it again today and can not make it work, errors in the console as follows:

Failed to load resource: net::ERR_FILE_NOT_FOUND file:///C:/Users/Stan/AppData/Local/Programs/Terminus/resources/app.asar/dist/[object%20Module]

```
ERROR Error: No option with key "cursorWidth"
    at e.getOption (xterm.js:1)
    at e.getOption (xterm.js:1)
    at e._renderBarCursor (xterm-addon-webgl.js:1)
    at e._render (xterm-addon-webgl.js:1)
    at e.onGridChanged (xterm-addon-webgl.js:1)
    at eval (xterm-addon-webgl.js:1)
    at Array.forEach (<anonymous>)
    at e.renderRows (xterm-addon-webgl.js:1)
    at t._renderRows (xterm.js:1)
    at eval [as _renderCallback] (xterm.js:1)
    at e._innerRefresh (xterm.js:1)
    at eval (xterm.js:1)
    at ZoneDelegate.invokeTask (C:\Users\Stan\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:423)
    at Object.onInvokeTask (C:\Users\Stan\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:17334)
    at ZoneDelegate.invokeTask (C:\Users\Stan\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:422)
    at Zone.runTask (C:\Users\Stan\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:195)
    at ZoneTask.invokeTask (C:\Users\Stan\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:498)
    at ZoneTask.invoke (C:\Users\Stan\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:487)
    at timer (C:\Users\Stan\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\zone.js\dist\zone.js:2281)
    at sentryWrapped (C:\Users\Stan\AppData\Local\Programs\Terminus\resources\app.asar\dist\sentry.js:1765)
```
file:///C:/Users/Stan/AppData/Local/Programs/Terminus/resources/app.asar/dist/index.html?1

C:\Users\Stan\AppData\Local\Programs\Terminus\resources\app.asar\node_modules\@angular\core\bundles\core.umd.js:15768 ERROR Error: Cannot find module './functions/gt'
    at webpackEmptyContext (C:\Users\Stan\AppData\Local\Programs\Terminus\resources\builtin-plugins\terminus-plugin-manager\dist\index.js:879)

my config file:

```yaml
ssh: {}
hotkeys:
  shell: {}
  profile: {}
terminal:
  colorScheme: &ref_0
    name: hyper-snazzy
    foreground: '#eff0eb'
    background: '#282a36'
    cursor: '#97979b'
    colors:
      - '#282a36'
      - '#ff5c57'
      - '#5af78e'
      - '#f3f99d'
      - '#57c7ff'
      - '#ff6ac1'
      - '#9aedfe'
      - '#f1f1f0'
      - '#686868'
      - '#ff5c57'
      - '#5af78e'
      - '#f3f99d'
      - '#57c7ff'
      - '#ff6ac1'
      - '#9aedfe'
      - '#eff0eb'
  cursor: beam
  cursorBlink: false
  environment: {}
  shell: wsl-Ubuntu
  autoOpen: true
  frontend: xterm-webgl
  background: theme
  useConPTY: true
  workingDirectory: 'C:\'
  copyOnSelect: true
  profile: wsl-ubuntu
  customColorSchemes:
    - *ref_0
appearance:
  theme: Standard
  vibrancy: false
  opacity: 1
  frame: thin
  vibrancyType: blur
enableAnalytics: false
titleControl:
  replacePattern: \scmnd \cmd
enableWelcomeTab: false
pluginBlacklist:
  - ssh
```
