### ISSUE TITLE
[Windows] Can't type in terminal

### ISSUE THREAD

**Issue by Ploppy3** [Eugeny/terminus#2004]
I can't type in terminal (terminus-1.0.99)

A previous installation worked but the new one does not.

This issue was [reported mid June](https://github.com/Eugeny/terminus/issues/1179), and was aggressively closed, a common problem on many repos.

**Edit:** Can't type in SSH either

![image](https://user-images.githubusercontent.com/7990765/72441130-7085b400-37aa-11ea-921b-e03541c5a075.png)

![image](https://user-images.githubusercontent.com/7990765/72441372-db36ef80-37aa-11ea-82d9-6b64ab0084bf.png)

**Comment by fle108** [comment]
same here. roll back to 0.98

**Comment by Ploppy3** [comment]
@fle108 with 0.98 terminus is loading, though I'm still unable to type.

![image](https://user-images.githubusercontent.com/7990765/72444100-b98c3700-37af-11ea-901c-7781f917a413.png)

**Comment by Eugeny** [comment]
@Ploppy3 the June issue is unrelated to this. There wasn't enough actionable info for me to produce a fix.

Your second trace refers to a malformed hotkeys config

**Comment by Ploppy3** [comment]
@Eugeny I did reset the config:

```
hotkeys:
  settings:
    - 'Ctrl-,'
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  new-tab:
    - Ctrl-Shift-T
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  shell:
    __nonStructural: true
  profile:
    __nonStructural: true
  ssh:
    - Alt-S
  new-window:
    - Ctrl-Shift-N
  toggle-window:
    - Ctrl+Space
  toggle-fullscreen:
    - F11
  close-tab:
    - Ctrl-Shift-W
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  split-right:
    - Ctrl-Shift-E
  split-bottom:
    - Ctrl-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - Ctrl-Alt-Right
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-up:
    - Ctrl-Alt-Up
  pane-nav-left:
    - Ctrl-Alt-Left
  close-pane: []
terminal:
  font: Consolas
  shell: clink
  profile: cmd-clink
  rightClick: menu
  pasteOnMiddleClick: true
  copyOnSelect: false
  frontend: xterm
  autoOpen: false
  fontSize: 14
  fallbackFont: null
  linePadding: 0
  bell: 'off'
  bracketedPaste: false
  background: theme
  ligatures: false
  cursor: block
  cursorBlink: true
  customShell: ''
  scrollOnInput: true
  workingDirectory: ''
  alwaysUseWorkingDirectory: false
  altIsMeta: false
  colorScheme:
    __nonStructural: true
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  customColorSchemes: []
  environment: {}
  profiles: []
  useConPTY: true
  recoverTabs: true
ssh:
  connections: []
  options: {}
pluginBlacklist: []
appearance:
  dock: 'off'
  dockScreen: current
  dockFill: 0.5
  tabsLocation: top
  cycleTabs: true
  theme: Standard
  frame: thin
  css: '/* * { color: blue !important; } */'
  opacity: 1
  vibrancy: false
  vibrancyType: blur
enableAnalytics: true
enableWelcomeTab: true
electronFlags:
  - - force_discrete_gpu
    - '0'
enableAutomaticUpdates: true
```
