### ISSUE TITLE
Column selection mode

### ISSUE THREAD

**Issue by LeonardoDG2084** [Eugeny/terminus#214]
Hi, 
First of all, this app is amazing and soon it will a definitive app terminal, but i like to select in column mode.

PS: If is possible, to increase the size of the line of "indicator of activity" on the other tab, is too tiny.... 

Thanks!!

**Comment by Eugeny** [comment]
Meanwhile, you can make the indicator thicker with this custom CSS:

```css
tab-header.has-activity:not(.active) {
    border-top-width: 3px;
}
```
