### ISSUE TITLE
Save button not working in Adding a SSH connection

### ISSUE THREAD

**Issue by TrackRunny** [Eugeny/terminus#2203]
Version: 1.0.104
OS: Kubuntu 18.04
Issue: When I try to add a SSH connection and hit the save button it won't work at all and nothing gets saved.

**Comment by Eugeny** [comment]
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by TrackRunny** [comment]
Heres the log.
```
/opt/Terminus/resour…es/core.umd.js:4034 ERROR TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at EditConnectionModalComponent.save (editConnectionModal.component.ts:98)
    at Object.eval [as handleEvent] (EditConnectionModalC…t.ngfactory.js:1285)
    at Object.handleEvent (/opt/Terminus/resour…s/core.umd.js:30925)
    at Object.handleEvent (/opt/Terminus/resour…s/core.umd.js:31470)
    at dispatchEvent (/opt/Terminus/resour…s/core.umd.js:21495)
    at /opt/Terminus/resour…s/core.umd.js:30134
    at HTMLButtonElement.<anonymous> (/opt/Terminus/resour…-browser.umd.js:758)
    at ZoneDelegate.invokeTask (/opt/Terminus/resour…js/dist/zone.js:431)
    at Object.onInvokeTask (/opt/Terminus/resour…s/core.umd.js:27882)
    at ZoneDelegate.invokeTask (/opt/Terminus/resour…js/dist/zone.js:430)
    at Zone.runTask (/opt/Terminus/resour…js/dist/zone.js:198)
    at ZoneTask.invokeTask [as invoke] (/opt/Terminus/resour…js/dist/zone.js:513)
    at invokeTask (/opt/Terminus/resour…s/dist/zone.js:1671)
    at HTMLButtonElement.globalZoneAwareCallback (/opt/Terminus/resour…s/dist/zone.js:1697)
    at HTMLButtonElement.sentryWrapped (/opt/Terminus/resour…dist/sentry.js:1840)
```

**Comment by manjotsc** [comment]
Windows 10
I same problem too, but in my case save button works when adding new connection, but save button doesn't work after for editing any thing in it.

**Comment by Eugeny** [comment]
Is this the only error in the dev console you're seeing? Could you please post your config file?

**Comment by TrackRunny** [comment]
Here is my config file:

```yml
hotkeys:
  shell: {}
  profile: {}
terminal:
  colorScheme:
    name: MaterialDark
    foreground: '#e5e5e5'
    background: '#232322'
    cursor: '#16afca'
    colors:
      - '#212121'
      - '#b7141f'
      - '#457b24'
      - '#f6981e'
      - '#134eb2'
      - '#560088'
      - '#0e717c'
      - '#efefef'
      - '#424242'
      - '#e83b3f'
      - '#7aba3a'
      - '#ffea2e'
      - '#54a4f3'
      - '#aa4dbc'
      - '#26bbd1'
      - '#d9d9d9'
  environment: {}
  ligatures: false
  background: theme
  frontend: xterm
ssh:
  connections: []
appearance:
  theme: Gruvbox
  tabsLocation: top
  frame: native
  css: '/* * { color: red !important; } */'
pluginBlacklist: []
enableAnalytics: false
enableWelcomeTab: false
serial: {}
```

I get this error when I click the ssh button inside the settings:

```js
/opt/Terminus/resour…es/core.umd.js:4034 ERROR Error: Uncaught (in promise): Error: The name org.freedesktop.secrets was not provided by any .service files
Error: The name org.freedesktop.secrets was not provided by any .service files
    at resolvePromise (/opt/Terminus/resour…js/dist/zone.js:836)
    at /opt/Terminus/resour…js/dist/zone.js:750
    at rejected (tslib.es6.js:63)
    at ZoneDelegate.invoke (/opt/Terminus/resour…js/dist/zone.js:396)
    at Object.onInvoke (/opt/Terminus/resour…s/core.umd.js:27894)
    at ZoneDelegate.invoke (/opt/Terminus/resour…js/dist/zone.js:395)
    at Zone.run (/opt/Terminus/resour…js/dist/zone.js:153)
    at /opt/Terminus/resour…js/dist/zone.js:894
    at ZoneDelegate.invokeTask (/opt/Terminus/resour…js/dist/zone.js:431)
    at Object.onInvokeTask (/opt/Terminus/resour…s/core.umd.js:27882)
    at ZoneDelegate.invokeTask (/opt/Terminus/resour…js/dist/zone.js:430)
    at Zone.runTask (/opt/Terminus/resour…js/dist/zone.js:198)
    at drainMicroTaskQueue (/opt/Terminus/resour…js/dist/zone.js:611)
```

And this error when I try to hit save:

```js
/opt/Terminus/resour…es/core.umd.js:4034 ERROR TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at EditConnectionModalComponent.save (editConnectionModal.component.ts:98)
    at Object.eval [as handleEvent] (EditConnectionModalC…t.ngfactory.js:1285)
    at Object.handleEvent (/opt/Terminus/resour…s/core.umd.js:30925)
    at Object.handleEvent (/opt/Terminus/resour…s/core.umd.js:31470)
    at dispatchEvent (/opt/Terminus/resour…s/core.umd.js:21495)
    at /opt/Terminus/resour…s/core.umd.js:30134
    at HTMLButtonElement.<anonymous> (/opt/Terminus/resour…-browser.umd.js:758)
    at ZoneDelegate.invokeTask (/opt/Terminus/resour…js/dist/zone.js:431)
    at Object.onInvokeTask (/opt/Terminus/resour…s/core.umd.js:27882)
    at ZoneDelegate.invokeTask (/opt/Terminus/resour…js/dist/zone.js:430)
    at Zone.runTask (/opt/Terminus/resour…js/dist/zone.js:198)
    at ZoneTask.invokeTask [as invoke] (/opt/Terminus/resour…js/dist/zone.js:513)
    at invokeTask (/opt/Terminus/resour…s/dist/zone.js:1671)
    at HTMLButtonElement.globalZoneAwareCallback (/opt/Terminus/resour…s/dist/zone.js:1697)
    at HTMLButtonElement.sentryWrapped (/opt/Terminus/resour…dist/sentry.js:1840)
```
