### ISSUE TITLE
xterm (WebGL) seems color not right

### ISSUE THREAD

**Issue by yurenchen000** [Eugeny/terminus#2210]
## xterm (WebGL)

![image](https://user-images.githubusercontent.com/8458213/75816642-88ec7500-5dd0-11ea-8e95-bd49b9fd42a6.png)

![image](https://user-images.githubusercontent.com/8458213/75816711-ab7e8e00-5dd0-11ea-94c6-d7d494347c29.png)

## xterm or hterm

![image](https://user-images.githubusercontent.com/8458213/75816781-cc46e380-5dd0-11ea-88d5-a83c97ac8978.png)

![image](https://user-images.githubusercontent.com/8458213/75816832-dec11d00-5dd0-11ea-9497-72ad939eb769.png)

**Comment by ChipwizBen** [comment]
I had this same problem. You need to set "Terminal background" to "From colour scheme".

**Comment by yurenchen000** [comment]
> 
> 
> I had this same problem. You need to set "Terminal background" to "From colour scheme".

I had try `From colour scheme`,  result same.
  I use the default color settings.

```yml
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
```

dig again, found something,
## seems xterm(webgl)  doesn't render `#000000` right
 try with `#000001` got some corrupt display:

![image](https://user-images.githubusercontent.com/8458213/76343954-c5bdec00-633b-11ea-8785-c107732fe0fc.png)

 try other color, `#000010` seems fine:

![image](https://user-images.githubusercontent.com/8458213/76343816-9d35f200-633b-11ea-998b-db9cb57c7780.png)

## seems xterm(webgl) doesn't render `rgba` alpha right
replace `rgba(255, 255, 255, 0.2)`  with fix color `#4d555d`, seems fine:

![image](https://user-images.githubusercontent.com/8458213/76344684-efc3de00-633c-11ea-9eb8-49e581489bd1.png)
