### ISSUE TITLE
tmux not working on Windows (MSYS2)

### ISSUE THREAD

**Issue by gigi206** [Eugeny/terminus#2319]
Install msys2 and tmux:
```
$pacman -S tmux
```

```
gigi@portable MINGW64 ~
$ tmux
open terminal failed: not a terminal
```

Works well with mintty (default MSYS2 terminal).

Extract config.yaml:
```yaml
    - name: MSYS2
      sessionOptions:
        command: 'C:\VSCode-Anywhere\apps\scoop\apps\msys2\current\usr\bin\bash.exe'
        args:
          - '--login'
          - '-i'
        env:
          MSYSTEM: MSYS
          XTERM: xterm-256color
        runAsAdministrator: false
      color: ''
```
