### ISSUE TITLE
Simple Q: How do I insert a return character to ssh login script

### ISSUE THREAD

**Issue by yelled1** [Eugeny/terminus#2447]
Hi:

I am trying to send ```cmd -new_console:d:C:\Prj cmd /E:ON /k ""%ConEmuDir%\..\init.bat``` on login, which turns terminal into a Cmder at the login & Set up one in Scripts as below. Do I need to add '\n' or '\r' or some different thing?
```
      scripts:
        - expect: 'OtherUser> '
          send: '%ConEmuDir%\..\init.bat '
          isRegex: false
          optional: false
      privateKey: 'C:\Users\myUser\.ssh\id_rsa'
      x11: false
```
also tried 
```
          send: '%ConEmuDir%\..\init.bat \n'
          send: '%ConEmuDir%\..\init.bat \r'
```  
Right now I get the %ConEmuDir%\..\init.bat but have to manually press "return key"
C:\Users\OtherUser>%ConEmuDir%\..\init.bat (cursor blinks)
Not bad but...
Thanks,

Yelled1

Thanks much,

yelled
