### ISSUE TITLE
It is hard to see the pane divider

### ISSUE THREAD

**Issue by nasatome** [Eugeny/terminus#2602]
![image](https://user-images.githubusercontent.com/18271791/82403834-6c51f780-9a25-11ea-8449-0f06b6d49442.png)

when you divide the terminal into several panels it is very difficult to see in the dark mode, when you are running commands with similar outputs (tail -f file.log) you easily get confused which terminal gives the log you want

this microsoft terminal issue is very similar:
 https://github.com/microsoft/terminal/issues/2377#issue-479141537

you should be able to change from the appearance menu the color of that dividing line

if I had this shade all the time, or even more, even if it's a 2px line but of a contrasting color it would be much better (as a terminator)

![image](https://user-images.githubusercontent.com/18271791/82404131-1d589200-9a26-11ea-9a22-aed90cb7eb99.png)

**Comment by Eugeny** [comment]
You can change the divider background with custom CSS in Settings:

```split-tab-spanner{
  background: black;
}```

**Comment by nasatome** [comment]
![image](https://user-images.githubusercontent.com/18271791/82531958-f96c7d80-9b05-11ea-8b23-2128bf18629d.png)


thanks!!!

**Comment by kirkbross** [comment]
So cool!!!!! :) :)

**Comment by CharlesOkwuagwu** [comment]
> You can change the divider background with custom CSS in Settings:
> 
> ```
> split-tab-spanner{
>   background: black;
> }
> ```

Can we adjust other appearance css of  the `split-tab-spanner`?
```css
split-tab-spanner{
  background: black;
  height: 3px; // like this one ?
}
```

**Comment by mkubdev** [comment]
> > You can change the divider background with custom CSS in Settings:
> > ```
> > split-tab-spanner{
> >   background: black;
> > }
> > ```
> 
> Can we adjust other appearance css of the `split-tab-spanner`?
> 
> ```css
> split-tab-spanner{
>   background: black;
>   height: 3px; // like this one ?
> }
> ```

Hello!

Yes you can use this custom CSS:

```css
split-tab-spanner.v {
	height: 3px !important;
}
```
```css
split-tab-spanner.h {
	width: 3px !important;
}
```

**Comment by appzi** [comment]
Going a bit further
```css
split-tab-spanner {
    transition: background-color 0.3s ease-in !important;
    border: 3px solid transparent !important;

    background-clip: content-box !important;
    background: rgba(255, 255, 255, 0.2);
}

split-tab-spanner:hover,
split-tab-spanner:active {
    background: #eee !important;
    background-clip: content-box !important;
}

split-tab-spanner.v {
    height: 14px !important;
    padding: 2px 6px;
}

split-tab-spanner.h {
    width: 14px !important;
    padding: 5px 2px;
}
```

![Tabby_EXjKUxBxGV](https://github.com/Eugeny/tabby/assets/35664760/3a6f0e29-369b-4ff3-bb41-1c532ff0b3e4)
