### ISSUE TITLE
After clicking `Close and never show again` on the `Welcome` page, several serious faults occurred.

### ISSUE THREAD

**Issue by himejisyana** [Eugeny/terminus#2624]
Version: 1.0.111
Platform: win32 10.0.18363
Plugins: clickable-links

After I click the `Close and never show again` button,

- The tab bar is moved to the bottom, although the value is `Top` in the settings:

  ![image](https://user-images.githubusercontent.com/18693190/82787278-a8a7ac80-9e98-11ea-85a3-ec4668b5d251.png)

- A strange horizontal line appears on the tab bar:

  ![image](https://user-images.githubusercontent.com/18693190/82787457-03d99f00-9e99-11ea-9caf-9768b53b34d0.png)

- The appearance of the settings page becomes very strange:

  ![image](https://user-images.githubusercontent.com/18693190/82787613-5e72fb00-9e99-11ea-9994-b5398c814da8.png)

  ![image](https://user-images.githubusercontent.com/18693190/82787670-7e0a2380-9e99-11ea-97de-9947b5532cb3.png)

- When I click the `GitHub` button and the `Report a problem` button, it no longer works:

  ![image](https://user-images.githubusercontent.com/18693190/82787783-c590af80-9e99-11ea-8904-bca12562c95e.png)

This is the configuration when the issue occurs:

``` YAML
terminal:
  profile: default-(powershell-core)
  ligatures: true
  font: Fira Code
  bell: visual
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    selection: null
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  environment: {}
hotkeys:
  shell: {}
  profile: {}
serial: {}
ssh: {}
appearance: {}
enableWelcomeTab: false
pluginBlacklist: []
```
