### ISSUE TITLE
window dragging on Windows 10

### ISSUE THREAD

**Issue by andrewboie** [Eugeny/terminus#2942]
For some reason, the Terminus window drags VERY slowly on my Windows 10 machine. This is a beefy computer with an AMD 3950X and an NVIDIA 2070. Never seen any other application do anything like this. Note the double mouse cursors!

Video:

https://youtu.be/lTsPWZFwlug

Reproducible with release 1.0.119.

My config:

```
terminal:
  environment: {}
  colorScheme:
    name: Bright Lights
    foreground: '#b3c9d7'
    background: '#191919'
    cursor: '#f34b00'
    colors:
      - '#191919'
      - '#ff355b'
      - '#b7e876'
      - '#ffc251'
      - '#76d4ff'
      - '#ba76e7'
      - '#6cbfb5'
      - '#c2c8d7'
      - '#191919'
      - '#ff355b'
      - '#b7e876'
      - '#ffc251'
      - '#76d5ff'
      - '#ba76e7'
      - '#6cbfb5'
      - '#c2c8d7'
  font: Fira Code Medium Regular
  ligatures: false
  fontSize: 12
  copyOnSelect: true
  bracketedPaste: true
  bell: visual
  background: colorScheme
  fallbackFont: ''
  frontend: hterm
  profile: powershell
hotkeys:
  shell: {}
  profile: {}
  pane-nav-up:
    - - Ctrl-Alt-Up
    - - Alt-Up
  pane-nav-down:
    - - Ctrl-Alt-Down
    - - Alt-Down
  pane-nav-left:
    - - Ctrl-Alt-Left
    - - Alt-Left
  pane-nav-right:
    - - Ctrl-Alt-Right
    - - Alt-Right
serial: {}
ssh:
  connections:
    - name: apboie-mobl4
      group: null
      host: apboie-mobl4
      port: 22
      user: apboie
      algorithms:
        hmac:
          - hmac-sha2-256
          - hmac-sha2-512
          - hmac-sha1
        kex:
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group16-sha512
          - diffie-hellman-group18-sha512
          - diffie-hellman-group14-sha1
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ssh-ed25519
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - ssh-rsa
      scripts: []
      privateKey: 'C:\Users\andre\Documents\id_rsa'
appearance:
  vibrancyType: fluent
  vibrancy: true
  tabsLocation: top
  theme: Standard
  frame: native
enableWelcomeTab: false
pluginBlacklist: []

```
