### ISSUE TITLE
Window scrolling stops after about 1800 lines [PowerShell]

### ISSUE THREAD

**Issue by cdhunt** [Eugeny/terminus#340]
I have noticed after using Terminus with a new window session for a while that auto-scrolling stops working after a while. After some simple testing, it looks like after about 1800 lines of output, the scrolling freezes.

Terminus: Alpha 46
OS: Windows 10 Enterprise 6299.15.amd64fre.rs3_release.170928-1534
Powershell: 5.1.16299.251 and 6.1.0-preview.2

**Steps to Reproduce:**

```powershell
1..2100 | % { write-host "line $_"}
```

**Comment by princemaple** [comment]
FYI seems fine to me
Terminus: Alpha 47
Powershell: 5.1.17134.48
Windows: 10.0.17134

**Comment by cdhunt** [comment]
Here's my config.

```yaml
hotkeys:
  toggle-window:
    - - Ctrl-Shift-Space
terminal:
  font: Fira Code
  colorScheme:
    name: Molokai
    foreground: '#bbbbbb'
    background: '#121212'
    cursor: '#bbbbbb'
    colors:
      - '#121212'
      - '#fa2573'
      - '#98e123'
      - '#dfd460'
      - '#1080d0'
      - '#8700ff'
      - '#43a8d0'
      - '#bbbbbb'
      - '#555555'
      - '#f6669d'
      - '#b1e05f'
      - '#fff26d'
      - '#00afff'
      - '#af87ff'
      - '#51ceff'
      - '#ffffff'
  shell: powershell
  autoOpen: true
  cursor: underline
  cursorBlink: false
  rightClick: paste
  copyOnSelect: true
  bell: visual
  background: theme
appearance: {}
```
