### ISSUE TITLE
Cycle through focused panes

### ISSUE THREAD

**Issue by pythoninthegrass** [Eugeny/terminus#3417]
Hi @Eugeny.

Excellent terminal. Head and shoulders above anything else I've used in Windows. 

Finally making the switch from years on cmder. I've almost got my `config.yaml` at parity with iTerm2 on the Mac side.

Aside from being able to split panes natively (#49), navigating via keystrokes is ideal. I mapped it this way:
```
hotkeys:
 ...
  split-right:
    - - Ctrl-D
  split-bottom:
    - - Ctrl-Shift-D
  pane-nav-left:
    - - 'Ctrl-['
  pane-nav-right:
    - - 'Ctrl-]'
```
However, to my knowledge it appears that it only moves in cardinal directions _without_ cycling across all available panes. Would it be possible to loop back to top and bottom panes without explicitly mapping those shortcuts?

![2021-02-05 23_58_10-lance@ncase_  _l-ste_Documents_GitHub_simple_news](https://user-images.githubusercontent.com/4097471/107110570-811e2780-680e-11eb-8ca4-71b38a612d2f.png)
