### ISSUE TITLE
Setting a background image

### ISSUE THREAD

**Issue by alminisl** [Eugeny/terminus#3470]
So, I've tried this 
```
tab-body.active { 
  background: url("/home/user/Pictures/someimage.png") !important;
}


x-screen {
    background: url("/home/user/Pictures/someimage.png");
    background-size: cover;
}
```
However, both issues are not working, am I doing something wrong here ? Those are the top results when I search how to change the background in Terminus. 

Thanks!

**Comment by qxde** [comment]
Your method is right, at least in my try
![WVQ_%ZY49N0}LS~})7030ZM](https://user-images.githubusercontent.com/47294142/108617824-3b8b6c80-7454-11eb-8f53-bd4c51703967.png)


![VRQ(C$}3$DPH(P9Q~(WH40T](https://user-images.githubusercontent.com/47294142/108617888-96bd5f00-7454-11eb-814d-e7a2c48d5648.png)

**Comment by gflujan** [comment]
I just want to add this note here for any Windows users that might run into this...

If you're setting your background image, you need to provide `file:///` as the prefix before your full absolute path. If you don't, the app will interpret a path like `F:/Cloud/Dropbox/1-Apps/_global/wallpapers/wall-004.jpg` as relative to Tabby's `dist` folder within the app.

Example: `file:///C:/Program%20Files/Tabby/resources/app.asar/dist/F:\Cloud\Dropbox\1-Apps\_global\wallpapers\wall-004.jpg`. 

And for my machines, I added the CSS to the `.xterm-viewport` class (on Mac and Windows) so far with success. 

```
.xterm-viewport {
   background-image: url("file:///F:/Cloud/Dropbox/1-Apps/_global/wallpapers/wall-004.jpg");
   background-repeat: no-repeat;
   background-size: 100vw 100vh;
   opacity: 0.5;
}
```

**Comment by spiritfox358** [comment]
> 

You're right, I'm successed in your way

**Comment by gflujan** [comment]
I had to make a tweak recently with the latest Tabby updates:

```css
.xterm-viewport {
   background-image: url("/path/to/your/image/here");
   background-repeat: no-repeat;
   background-position: 45%;
   background-size: auto 100vh;
   filter: opacity(50%);
   opacity: 0.2;
   z-index: 1; <-- THIS IS THE NEW CHANGE/ADDITION
}
```
