### ISSUE TITLE
With custom css the scrollbar can be hidden but it still occupies space

### ISSUE THREAD

**Issue by clarkwang** [Eugeny/terminus#3611]
With the following css I can hide the vertical scrollbar but it still occupies space (see the screenshot) even it's invisible. Can we add an option to disable the scrollbar completely so we can get 2 more columns?

```css
::-webkit-scrollbar {
    display: none;
}
```

![image](https://user-images.githubusercontent.com/157076/111256793-d42c9b00-8654-11eb-9234-20d30b2d2f03.png)
