### ISSUE TITLE
Running terminus as admin in win 10 - only every second tab opens correctly

### ISSUE THREAD

**Issue by hummal** [Eugeny/terminus#375]
### Specs
OS: Windows 10 x64
Terminus Version: Alpha 48

### Problem
If I start Terminus as admin on Windows 10 it only opens every second tab correctly. The others still pending in nowhere. Gif attached to have a visual idea of what I mean.

![terminus](https://user-images.githubusercontent.com/633711/42438088-543ebb9e-835f-11e8-9feb-badaa0240dfe.gif)

**Comment by Eugeny** [comment]
I can't seem to reproduce this - can you attach the logs?

**Comment by hummal** [comment]
Tell me how and I will provide them. Didn't find any logs

**Comment by Eugeny** [comment]
Thanks. Are you using cmder as the shell?

**Comment by hummal** [comment]
Yes!

```
terminal:
  shell: cmder
  customShell: cmd.exe /s /k %ConEmuDir%\..\init.bat
  workingDirectory: 'D:\Repositories'
  copyOnSelect: true
  bracketedPaste: true
```
