### ISSUE TITLE
better handling for large numbers of ssh connections

### ISSUE THREAD

**Issue by kbjr** [Eugeny/terminus#403]
I have something like 200 SSH connections saved at any given time.

First, when you have a ton of connections, the UI actually breaks. I had to apply some custom CSS to make the connection selector actually scroll instead of flowing off into nowhere.

#### My hacky fix for large SSH connection list:

```css
input[placeholder^='Quick connect'] + div.list-group.mt-3,
.list-group.mt-3.ng-star-inserted + div.list-group.mt-3 {
    max-height: 800px;
    overflow-y: auto;
}
```

Second, more of a nice to have thing, it would be really nice to have some way of quickly getting to the connection that I want, rather then having to scroll through a large list looking for it, like a fuzzy search/filter option.
