### ISSUE TITLE
Need support for hotkey combination

### ISSUE THREAD

**Issue by John-Theo** [Eugeny/terminus#494]
Version: 1.0.0-alpha.62
Platform: win32 10.0.14393
Plugins: 

I'm using `screen` on my remote ubuntu, it use Ctrl+A, Ctrl+D to detach. Many ssh tool support this functionality, I'm looking forward to meet it on Terminus!

**Comment by Eugeny** [comment]
Terminus uses screen internally for tab persistence - disable it or set it to `tmux` under settings, and remove the standard Ctrl-A hotkeys.

**Comment by davidone** [comment]
I don't see this option anywhere. Where is it?

**Comment by Eugeny** [comment]
@davidone if you're using a recent version, Ctrl-A hotkeys shouldn't be mapped on Windows at all. You should be able to use `screen` right away.

**Comment by davidone** [comment]
I'm using tmux (with Ctrl+a as binding sequence).

This is my config file:
```
hotkeys:
  copy:
    - Ctrl-c
  paste:
    - Ctrl-v
  settings:
    - Ctrl-s
  zoom-in:
    - Ctrl-+
  zoom-out:
    - Ctrl--
  previous-word: []
  next-word: []
  delete-previous-word: []
  delete-next-word: []
  clear: []
  reset-zoom: []
  new-tab: []
  ctrl-c: []
  shell:
    wsl:
      - Ctrl-n
  next-tab:
    - Ctrl-ArrowRight
  previous-tab:
    - Ctrl-ArrowLeft
ssh: {}
terminal:
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  environment: {}
  shell: wsl
  workingDirectory: ''
  autoOpen: true
  bell: visual
  background: theme
  bracketedPaste: false
  copyOnSelect: false
  altIsMeta: false
  ligatures: false
appearance:
  vibrancy: false
  opacity: 1
  frame: thin
  dock: 'off'
  theme: Windows 10
  vibrancyType: blur
enableAnalytics: false
```

and this is (part of) my .tmux.conf:
```
# Use CTRL-A as prefix-key (screen-like)
set -g prefix C-a
unbind C-b
bind C-a send-prefix
```
