### ISSUE TITLE
Margins between edges of window and text - I wanna change them

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [Eugeny/terminus#5439]
**Is your feature request related to a problem? Please describe.**
You see this gap?
![image](https://user-images.githubusercontent.com/14184826/148839908-24c22e55-0b89-4755-b9dd-165b58b7aed3.png)

I wanna change it.

**Describe the solution you'd like**
Add a slider to change it. Also probably make it changeable by themes and/or plugins.

**Describe alternatives you've considered**
N/A

**Additional context**
It's particularly visible if you use [`powerline`](https://github.com/powerline/powerline). Which I do.
![image](https://user-images.githubusercontent.com/14184826/148840090-b9e57c5f-0da4-49ab-b116-d54b4459eaf8.png)

**Comment by Eugeny** [comment]
The stock `Compact` theme has less padding. You can go further with this bit of custom CSS:

```css
terminaltab .content,
ssh-tab .content,
serial-tab .content {
    margin: 0 !important;
}
```
