### ISSUE TITLE
tmux bind key not working

### ISSUE THREAD

**Issue by davidone** [Eugeny/terminus#567]
I'm using Windows 10 + WSL + Terminus 1.0.1 with this config file:
```
hotkeys:
  copy:
    - Ctrl-Ins
  paste:
    - Shift-Ins
  settings:
    - Alt-s
  zoom-in:
    - Alt-+
  zoom-out:
    - Alt--
  previous-word: []
  next-word: []
  delete-previous-word: []
  delete-next-word: []
  clear: []
  reset-zoom: []
  new-tab: []
  ctrl-c:
    - Ctrl-C
  shell:
    wsl:
      - Alt-n
  next-tab:
    - Alt-ArrowRight
  previous-tab:
    - Alt-ArrowLeft
ssh: {}
terminal:
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  environment: {}
  shell: wsl
  workingDirectory: ''
  autoOpen: true
  bell: visual
  background: theme
  bracketedPaste: false
  copyOnSelect: false
  altIsMeta: false
  ligatures: false
appearance:
  vibrancy: false
  opacity: 1
  frame: thin
  dock: 'off'
  theme: Windows 10
  vibrancyType: blur
enableAnalytics: false
titleControl:
  replacePattern: ''
```

when I ssh to a remote machine and try to use tmux over there, it doesn't work (it seems tmux is not getting Control key at all). My tmux config file contains:
```
# Use CTRL-A as prefix-key (screen-like)
set -g prefix C-a
unbind C-b
bind C-a send-prefix
```

I saw this: https://github.com/Eugeny/terminus/issues/494, didn't help.
