### ISSUE TITLE
"Alt+=", used by emacs, is not passed to terminal, with or without "Alt as Meta key"

### ISSUE THREAD

**Issue by fanfan54** [Eugeny/terminus#571]
Hi,
I'm trying Terminus and I mainly use emacs for programming.
I found that many keystrokes didn't work on emacs (everything based on Alt), then I found that I had to check the option to use "Alt key as Meta key" in Terminus settings.

With or without enabling this, I still have issues with "Alt + =", which should display the number of characters/words in the selected region. I can select regions, I can copy paste, I can do every hotkey with Alt except "Alt + =".

I use Terminus 1.0.65 on Fedora (running as a standard user, not as root). Here is my config:
```
hotkeys:
  shell: {}
  new-tab:
    - - Ctrl-Shift-T
  zoom-out:
    - - Ctrl-Shift-6
  zoom-in: []
  close-tab:
    - - Ctrl-Shift-W
  next-tab:
    - - Ctrl-Tab
    - - Ctrl-PageDown
  previous-tab:
    - - Ctrl-Shift-Tab
    - - Ctrl-PageUp
  tab-1:
    - - Ctrl-Shift-1
  tab-2:
    - - Ctrl-Shift-2
  tab-3:
    - - Ctrl-Shift-3
  tab-4:
    - - Ctrl-Shift-4
  tab-5:
    - - Ctrl-Shift-5
  tab-6:
    - - Ctrl-Shift-6
  tab-7:
    - - Ctrl-Shift-7
  tab-8:
    - - Ctrl-Shift-8
  tab-9:
    - - Ctrl-Shift-9
  tab-10:
    - - Ctrl-Shift-0
terminal:
  colorScheme:
    name: Solarized Dark
    foreground: '#708284'
    background: '#001e27'
    cursor: '#708284'
    colors:
      - '#002831'
      - '#d11c24'
      - '#738a05'
      - '#a57706'
      - '#2176c7'
      - '#c61c6f'
      - '#259286'
      - '#eae3cb'
      - '#001e27'
      - '#bd3613'
      - '#475b62'
      - '#536870'
      - '#708284'
      - '#5956ba'
      - '#819090'
      - '#fcf4dc'
  frontend: hterm
  ligatures: false
  background: colorScheme
  cursor: block
  font: DejaVu Sans Mono
  fontSize: 16
  environment: {}
  shell: /bin/bash
  bell: visual
  bracketedPaste: false
  scrollOnInput: true
  altIsMeta: true
appearance:
  css: ''
  dock: 'off'
enableAnalytics: false
pluginBlacklist: []
vibrancy: true
vibrancyType: blur
titleControl: {}
```

Here is what I see on screen when I try every Alt keystroke in `cat` **with french (AZERTY) layout** (note that every key returns its uppercase equivalent in Terminus, like in QWERTY where you don't need Shift to write numbers, while xfce4-terminal displays the correct ones) :
```
Key          On Terminus              On xfce4-terminal
---------------------------------------------------------
Alt + ²           ^['                         ^[²
Alt + &           ^[1                         ^[&
Alt + é           ^[2                         ^[é
Alt + "           ^[3                         ^["
Alt + '           ^[4                         ^['
Alt + (           ^[5                         ^[(
Alt + -           ^[6                         ^[-
Alt + è           ^[7                         ^[è
Alt + _           ^[8                         ^[_
Alt + ç           ^[9                         ^[ç
Alt + à      (nothing)                        ^[à
Alt + )           ^_                          ^[)
Alt + =      (nothing)                        ^[=
```
I have the "Alt + =" issue on AZERTY and QWERTY layouts.
This keyboard shortcut, and every keyboard shortcut possible, work perfectly in xfce4-terminal.

**Comment by Eugeny** [comment]
Could you please check whether it works properly with the xterm frontend selected?

**Comment by fanfan54** [comment]
Hi, 
I retried with the xterm frontend, on Terminus 1.0.66, and now it works.
I can use Alt+= in emacs, and when I type keyboard shortcuts in cat, Alt+) now outputs ^[[ and Alt+= outputs ^[=

Sorry, I should've tried with both terminal frontends before posting.
The problem is solved for me.

**Comment by Eugeny** [comment]
No problem - I'm going to make xterm the default frontend in the future.

**Comment by nicexe** [comment]
I'm having a similar problem on windows. Alt+up and Alt+down does not work on weechat regardless of the "Alt as Meta key" setting.
I tried all frontend options with both "Alt as Meta key" enabled and disabled.
I made sure to restart terminus between tests and the problem still persists.

**Comment by nicexe** [comment]
This is what my configuration looks like:
```
hotkeys:
  profile: {}
  shell: {}
ssh: {}
terminal:
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  background: theme
  environment: {}
  profile: default-powershell-core
  bell: audible
  autoOpen: true
  copyOnSelect: true
  altIsMeta: true
  fallbackFont: STIX Two Math
  useConPTY: true
  frontend: xterm
  ligatures: true
appearance:
  theme: Compact
  vibrancy: true
  vibrancyType: fluent
  frame: thin
  opacity: 1
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist:
  - relaxed-theme
  - theme-gruvbox
  - theme-hype
  - theme-windows10
  - altair
  - quick-cmds
qc: {}
titleControl: {}

```
