### ISSUE TITLE
Home and End key don't work

### ISSUE THREAD

**Issue by NatoBoram** [Eugeny/terminus#639]
```yaml
OS: Windows 10 Pro x86_64
Host: System manufacturer
Kernel: 2.11.2(0.329/5/3)
Uptime: 18 hours, 10 mins
Shell: bash 4.4.23
Resolution: 1920x1080
DE: Aero
WM: Explorer
WM Theme: Roamed
CPU: Intel i5-3570K (4) @ 3.468GHz
GPU: NVIDIA GeForce GTX 660 Ti
Memory: 4302MiB / 8135MiB
```

Same as #255, but it was closed without a solution.

I checked my shortcuts, and the keys seems to be configured correctly.

![home](https://user-images.githubusercontent.com/10495562/52018192-8cb81480-24b7-11e9-894c-cdc09ab408d0.PNG)

Config : 

```yaml
terminal:
  workingDirectory: 'D:\natob'
  bell: audible
  ligatures: true
  shell: cmd
appearance:
  vibrancy: true
  vibrancyType: fluent
```

Moreover, the CTRL + Arrow keys are inputting `b` and `f` instead of skipping a word.
