### ISSUE TITLE
tmux bottom bar scroll each time the clock is refreshed

### ISSUE THREAD

**Issue by njordr** [Eugeny/terminus#712]
Hi.

Usually I use tmux on my remote servers, but if I run it with terminus, each time the clock in tmux updated, the bottom bar scroll up. Also not all the colors are displayed (there has to be a bottom bar all over the bottom side of the screen and one in the upper side)

Terminus run on win 10, remote servers ubuntu 18.04/16.04

![image](https://user-images.githubusercontent.com/4282925/54018972-e4fec800-4181-11e9-885c-803a895c4f21.png)

Terminus conf:
```
hotkeys:
  shell: {}
ssh: {}
terminal:
  colorScheme:
    name: Solarized Dark Higher Contrast
    foreground: '#9cc2c3'
    background: '#001e27'
    cursor: '#f34b00'
    colors:
      - '#002831'
      - '#d11c24'
      - '#6cbe6c'
      - '#a57706'
      - '#2176c7'
      - '#c61c6f'
      - '#259286'
      - '#eae3cb'
      - '#006488'
      - '#f5163b'
      - '#51ef84'
      - '#b27e28'
      - '#178ec8'
      - '#e24d8e'
      - '#00b39e'
      - '#fcf4dc'
  ligatures: true
  background: colorScheme
  environment: {}
  shell: git-bash
  autoOpen: true
  bracketedPaste: false
  font: Fira Code
  profiles: []
  scrollOnInput: false
  frontend: hterm
appearance:
  tabsLocation: bottom
  vibrancy: false
  vibrancyType: fluent
  opacity: 1
  theme: Hype
```

I tried with both xterm and hterm.

tmux conf attached if it could help.

[tmux.txt](https://github.com/Eugeny/terminus/files/2945088/tmux.txt)
