### ISSUE TITLE
How to use with msys2?

### ISSUE THREAD

**Issue by Peter-Optiway** [Eugeny/terminus#759]
If i just point the custom shell at `msys2.exe` it just opens the msys2 in a separate window.
if i use `C:\msys64\usr\bin\mintty /usr/bin/bash -l` the tab is just empty.

**Comment by Perry3D** [comment]
You can directly start the shell. In my example it is zsh (you can replace it with bash).
From my `config.yaml`:
```yaml
  profiles:
    - name: MSYS2
      sessionOptions:
        command: 'f:\Tools\msys2\usr\bin\zsh.exe'
        args:
          - '--login'
        env:
          HOME: /home/oli
          CHERE_INVOKING: '1'
          MSYSTEM: MINGW64
          MSYS2_PATH_TYPE: inherit
```
