### ISSUE TITLE
Shortcut capture not working correctly under macOS

### ISSUE THREAD

**Issue by yasinuslu** [Eugeny/terminus#823]
Hi, Thank you for this great terminal.

When I capture a shortcut in macOS, Terminus captures that shortcut with macOS characters like `'⌘-Shift-E`. These shortcuts work fine for local shortcuts like `next-tab` or `previous-tab`. But they don't work for global shortcuts like `toggle-window`.

If I capture a shortcut like in the following gif:

![Kapture 2019-05-19 at 0 40 21](https://user-images.githubusercontent.com/1007479/57975299-c1040200-79ce-11e9-8193-d299614c6e65.gif)

That shortcut doesn't work. I cannot use it for toggling Terminus window. But it works correctly if I replace `⌘` with `Command` in the config file:

```yaml
hotkeys:
  next-tab:
    - - '⌘-Shift-]'
  previous-tab:
    - - '⌘-Shift-['
  toggle-window:
    - - Command-`
    - - Command-Shift-E
```
The problem also occurs with the `⌥` character. But it works fine for `Ctrl`. I think you should somehow make exceptions for global shortcuts and record modifier names instead of macOS specific characters.
