### ISSUE TITLE
Docking moves the window outside the screen

### ISSUE THREAD

**Issue by k0tkin** [Eugeny/terminus#9]
I just changed Dock option to TOP (maybe) and now screen is gone only thumbnail is visible
re-installing didn't help 

![image](https://user-images.githubusercontent.com/8723741/27741732-57dc5a28-5dcb-11e7-923f-5bc268887e99.png)

**Comment by Eugeny** [comment]
Have you got multiple screens? What's the layout? Which screen did you pin the app to? Can you please post the content of `%APPDATA%\Terminus\window.json` ?

**Comment by k0tkin** [comment]
I found how to fix it
I have this issue when in config.yaml file dock: bottom but if I change it to 'off' everything is fine
And in windows, I need to change the value of x,y to Zero
```
{
	"windowBoundaries": {
		"x": 0,
		"y": -13108,
		"width": 1536,
		"height": 825
	}
}
```

```
terminal:
  shell: powershell.exe
  background: theme
  bell: 'off'
hotkeys: {}
appearance:
  tabsLocation: top
  frame: thin
  dock: 'off'
```
